# index:
#    path: /
#    controller: App\Controller\ArticleController::index
# test annotation routes
# about:
#     path: /about
#     controller: App\Controller\AboutController::about
#     methods: GET|HEAD

# book_list:
#     path: /books
#     # the controller value has the format 'controller_class::method_name'
#     controller: App\Controller\BookController::list
#     methods: GET|HEAD

# book_new:
#     path: /book/new
#     controller: App\Controller\BookController::new
#     methods: GET|POST

# book_edit:
#     path: /book/edit/{id}
#     controller: App\Controller\BookController::edit
#     methods: GET|POST

# book_show:
#     path: /book/{id}
#     controller: App\Controller\BookController::show
#     methods: GET|HEAD

# book_delete:
#     path: /book/delete/{id}
#     controller: App\Controller\BookController::delete
#     methods: DELETE
